name: Trigger CI

on:
  push:
    tags:
      - '*'

jobs:  
  trigger_ci:  
    runs-on: ubuntu-latest
    steps:  
      - name: Trigger CI Workflow
        env:
          GH_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
        run: |
          tagRef=`echo ${{ github.ref }} | awk -F'/' '{print $3}'`
          gh workflow run -R mturnaviotov/test-run blank.yml -f app-version=$tagRef
